name: Build Passing
on: pull_request
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - run: chmod +x gradlew
      - name: Execute Gradle build
        run: ./gradlew build
